### ISSUE TITLE
Erroneous .gitmodules

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ccpp-physics#165]
Hi, I believe this file is incorrect. There should be only one reference to rte-rrtmgp in `.gitmodules`:

https://github.com/ufs-community/ccpp-physics/blob/51452b8b52d5f3ded391847aefc21b086bb27b64/.gitmodules#L1

**Comment by dustinswales** [comment]
Yeah, that shouldn't be there. Thanks for pointing this out.
I added this by mistake during the repo reorganization. I will fix.
