### ISSUE TITLE
two submodules for rte-rrtmgp

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ccpp-physics#166]
Should one of these have been removed during the re-org?

https://github.com/ufs-community/ccpp-physics/blob/51452b8b52d5f3ded391847aefc21b086bb27b64/.gitmodules#L1-L7

**Comment by climbfuji** [comment]
Duplicate of https://github.com/ufs-community/ccpp-physics/issues/165

**Comment by DeniseWorthen** [comment]
Thanks Dom, I'll close this.
