### ISSUE TITLE
Improve the biases of radiative fluxes, cloud cover, and surface temperature in GFSv17

### ISSUE THREAD

**Issue by ChunxiZhang-NOAA** [ufs-community/ccpp-physics#21]
## Description
The biases of radiative fluxes, cloud cover, and surface temperature in GFSv17 are relatively large.

## Solution
By modifying  the Thompson microphysics scheme and its related part in the RRTMG(P) pre interstitial code, it can reduce the biases.

**Comment by grantfirl** [comment]
Fixed in https://github.com/ufs-community/ccpp-physics/pull/19
