### ISSUE TITLE
modify the conditional statement in hybrid EDMF PBL scheme

### ISSUE THREAD

**Issue by ChangHung-CWB** [ufs-community/ccpp-physics#31]
# Description
The conditional statement for calculating the Prandtl number were modified to correctly distinguish the boundary layer stability.
A more detailed description of modification and experiment results can be found in the attach file.
[modified hedmf.pdf](https://github.com/ufs-community/ccpp-physics/files/10357021/modified.hedmf.pdf)

**Comment by grantfirl** [comment]
@JongilHan66 determined that this is not a bug, so this issue can be closed.
