### ISSUE TITLE
Update scientific documentation for the UFS-SRW App v3.0.0 release

### ISSUE THREAD

**Issue by grantfirl** [ufs-community/ccpp-physics#96]
## Description
Scientific documentation is typically kept up-to-date at least on release schedules. 

## Solution
Update documentation to reflect scientific changes in supported suites, including any new schemes.

**Comment by DeniseWorthen** [comment]
@grantfirl could you please close this issue? Thanks.

**Comment by ligiabernardet** [comment]
@mkavulich Since @grantfirl is out, can you address this request? Tks

**Comment by mkavulich** [comment]
Closed via #91
